config/routes.rb
Rails.application.routes.draw do
  get 'stats/foodViewed'

  get 'order/index'

  get 'order/new'

  post 'order/new' => 'order#create'

  get 'order/thankyou' => 'order#thank_you'

  root 'welcome#index'

  get 'welcome/contact_us' => 'welcome#contact_us'

  get 'welcome/menu' => 'welcome#menu'

  get 'welcome/menu/:section' => 'welcome#menu'

  get 'order/new/:id' => 'order#new'

  post 'stats/foodViewed' => 'stats#foodViewed'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
end

app/models/food.rb
class Food < ActiveRecord::Base
	has_many :orders
	has_one :food_stat
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :food
  validates :name, :phone_number, :address, :presence => {:message => 'Please fill the %{value}'},
            :allow_nil => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  # GET /foods
  # GET /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1
  # GET /foods/1.json
  def show
  end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit
  end

  # POST /foods
  # POST /foods.json
  def create
    @food = Food.new(food_params)

    respond_to do |format|
      if @food.save
        format.html { redirect_to @food, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1
  # PATCH/PUT /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to @food, notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1
  # DELETE /foods/1.json
  def destroy
    @food.destroy
    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_food
      @food = Food.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def food_params
      params.require(:food).permit(:name, :description, :price, :section, :imageUrl)
    end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
    def new
        @order = Order.new
        @food_id = params['id']
    end

    def create
        @food_id = params[:food_id]
        @order = Order.new(order_param)
        food = Food.where({id: params[:food_id]})

        price = nil
        coupon = nil
        coupon_code = params[:order][:coupon_code]
        if coupon_code != ""
            coupon = Coupon.where({code: coupon_code}).first

            if coupon
                price = food.first.price * coupon.discount
            end
        end

        respond_to do |format|
            if (food.count == 0)
                format.html {redirect_to welcome_menu_path, alert: 'Fail to create your order due to food not found. Please choose another food!'}
            elsif coupon_code != "" && coupon == nil
                flash[:alert] = 'Coupon code does not exist.'
                format.html { render :action => :new, :food_id => @food_id }
            elsif @order.save
                @order.update_attribute(:food_id, @food_id)
                format.html {redirect_to order_thankyou_path(:order_id => @order.id, :food_id => @food_id, :update_price => price), notice: 'Order was successfully created.'}
            else
                format.html { render :action => :new, :food_id => @food_id }
                format.json { render json: @order.errors, status: :unprocessable_entity }
            end
        end
    end

    def thank_you
        @food = (Food.where :id => params[:food_id]).first
        @order = (Order.where :id => params[:order_id]).first
        @price = params[:update_price] ? params[:update_price] : @food.price
    end

    private
        def order_param
            params.require(:order).permit(:name, :phone_number, :address, :coupon_code).merge({food_id: params.require(:food_id)})
        end
end

app/controllers/stats_controller.rb
class StatsController < ApplicationController
    before_filter :parse_request
    def foodViewed
        food = Food.where(id: @json['id']).first

        if food
            count = food.num_of_viewed
            if !count
                count = 1
            end

            food.update_attribute(:num_of_viewed, count + 1)
        end

        render :text =>  @json['id']
    end

    private
        def parse_request
            @json = JSON.parse(request.body.read)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def activeClass(section)
        className = params[:section] == section ? 'active' : ''
        sprintf '<li role="presentation" class="%s %s">', section, className
    end
    helper_method :activeClass

    def setUrlParam(name, value)
        url = request.original_url
        uri = URI.parse(url)

        if uri.query != nil
            queryParams = CGI.parse(uri.query)

            if value != nil
                queryParams[name] = [value]
            else
                queryParams.except!(name)
            end

            result = sprintf('%s?', request.path)

            queryParams.each do |param|
                if result[-1, 1] != '?'
                    result += '&'
                end

                result += sprintf('%s=%s', param[0], param[1][0])
            end
        elsif 
            if value != nil
                result = sprintf('%s?%s=%s', request.path, name, value)
            else
                result = request.path
            end
        end
            
        result
    end
    helper_method :setUrlParam

    def index
    end

    def contact_us
    end

    def menu
        section = SECTIONS[0]
        if params[:section].present?
            section = params[:section]   
        end

        @foods = Food.where({section: section})

        if params[:filterBy] != nil
            filterBy = params[:filterBy].to_i
            @foods = @foods.where(type_of_cuisine: filterBy)
        end

        if params[:orderBy] != nil
            case params[:orderBy].to_i
                when SORT_OPTION_ID[:NAME_ASC]
                    @foods = @foods.order(:name)

                when SORT_OPTION_ID[:NAME_DESC]
                    @foods = @foods.order(name: :desc)
                    
                when SORT_OPTION_ID[:PRICE_ASC]
                    @foods = @foods.order(:price)
                    
                when SORT_OPTION_ID[:PRICE_DESC]
                    @foods = @foods.order(price: :desc)

                when SORT_OPTION_ID[:VIEWED_ASC]
                    @foods = @foods.order(:num_of_viewed)

                when SORT_OPTION_ID[:VIEWED_DESC]
                    @foods = @foods.order(num_of_viewed: :desc)
                    
            end    
        end
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/stats_helper.rb
module StatsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/foods/_form.html.erb
<%= form_for(@food) do |f| %>
  <% if @food.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@food.errors.count, "error") %> prohibited this food from being saved:</h2>

      <ul>
      <% @food.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.text_field :section %>
  </div>
  <div class="field">
    <%= f.label :imageUrl %><br>
    <%= f.text_area :imageUrl %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<h1>Editing Food</h1>

<%= render 'form' %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>

app/views/foods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Section</th>
      <th>Imageurl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.description %></td>
        <td><%= food.price %></td>
        <td><%= food.section %></td>
        <td><%= food.imageUrl %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Food', new_food_path %>

app/views/foods/new.html.erb
<h1>New Food</h1>

<%= render 'form' %>

<%= link_to 'Back', foods_path %>

app/views/foods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @food.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<p>
  <strong>Section:</strong>
  <%= @food.section %>
</p>

<p>
  <strong>Imageurl:</strong>
  <%= @food.imageUrl %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <title>Thuan's Restaurant</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'bootstrap', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'bootstrap_blue', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap.min', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'bootstrap-notify.min', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name%> <%= action_name%>">
    <nav class="navbar navbar-default">
        <div class="container-fluid">
                
                <div class="navbar-header">
                <button <button
                        type="button"
                        class="navbar-toggle collapsed"
                        data-toggle="collapse"
                        data-target="#navbar"
                        aria-expanded="false">
                <i class="fa fa-bars" style="color:#999;"></i>
                </button>
                <%= link_to 'Thuan\'s Restaurant', root_url, {:class => :'navbar-brand'} %>
            </div>
            <div id="navbar" class="navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li class="home"><%= link_to 'Home', root_url %></li>
                        <li class="menu"><%= link_to 'Menu', :controller => "welcome", :action => "menu" %></li>
                        <li class="contact_us"><%= link_to 'Contact', :controller => "welcome", :action => "contact_us" %></li>
                    </ul>
            </div>
        </div>
    </nav>

    <div class="container">
        <%= yield %>
    </div>

    <% if flash[:notice] %>
        <%= javascript_tag do %>
            $.notify("<%= flash[:notice] %>", { allow_dismiss: true, type: 'sucess' });
        <% end %>    
    <% end %>

    <% if flash[:alert] %>
        <%= javascript_tag do %>
            $.notify("<%= flash[:alert] %>", { allow_dismiss: true, type: 'danger' });
        <% end %>    
    <% end %>

</body>
</html>

app/views/order/_form.html.erb
<%= form_for @order, url: order_new_path, html: {role: 'form'} do |f| %>
	<%= hidden_field_tag 'food_id', @food_id %>
	<div class="form-group">
		<%= f.label :name %>
		<%= f.text_field :name, :class => 'form-control', :required => true %>
	</div>

	<div class="form-group">
		<%= f.label :phone_number %>
		<%= f.text_field :phone_number, :class => 'form-control', :required => true %>
	</div>

	<div class="form-group">
		<%= f.label :address %>
		<%= f.text_area :address, :class => 'form-control', :required => true %>
	</div>

	<div class="form-group">
		<%= f.label :coupon_code %>
		<%= f.text_field :coupon_code, :class => 'form-control' %>
	</div>

	<div class="action">
		<%= f.submit 'Order', :class => 'btn btn-primary' %>
	</div>
<% end %>

app/views/order/new.html.erb
<%= params[:alert] %>
<%= render 'form' %>

app/views/order/thank_you.html.erb
<div class="col-md-6 col-md-offset-3 order-content">
	<h3>Thank you for your order</h3>
	<div class='card order-details'> 
		<img class='card-img-top' src='<%= @food.imageUrl %>' alt='<%= @food.name %>'> 
		<div class='card-block'> 
			<h2 class='card-title'><%= @order.name %></h2> 
			<h4 class='card-text price'><%= number_to_currency(@price, precision: 1, unit: 'VND', format: '%n %u') %></h4> 
			<p class='card-text address'><%= @order.address %></p>
			<p class='card-text date'><%=  @order.created_at.to_formatted_s(:long_ordinal) %></p>
			<%= link_to 'Back to Menu', {:controller => 'welcome', :action => 'menu'}, {:class => 'btn btn-primary'} %>
		</div> 
	</div>
</div>

app/views/welcome/contact_us.html.erb
<div class="row">
    <div class="col-md-3 address">
        <h3>Contact Us</h3>
        <ul>
            <li><i class="fa fa-map-marker addr-icon"></i>No.23 Street 6</li>
            <li class="addr-detail">Binh Tan</li>
            <li class="addr-detail">Ho Chi Minh city</li>
            <li class="addr-detail">Vietnam</li>
            <li><i class="fa fa-phone addr-icon"></i>099 456 7788</li>
        </ul>
    </div>

    <div class="col-md-9 map">
        <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3919.5576526181617!2d106.61881385585961!3d10.768534432768824!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0000000000000000%3A0xf4c7206c2db75b62!2zQ8O0bmcgVHkgVG5oaCBTeCBUbSBEdiBExrDGoW5nIFRydW5nIFPGoW4!5e0!3m2!1sen!2s!4v1449074394194" width="100%" height="450" frameborder="0" style="border:0" allowfullscreen></iframe>
    </div>
</div>

<%= javascript_tag do %>
    $('#navbar li.contact_us').addClass('active');
<% end %>

app/views/welcome/index.html.erb
<div class="bg fullscreen"></div>
    <div class="content fullscreen">
        <h1>Welcome to Thuan's Restaurant,</h1>
        <h4>The top restaurant in Vietnam.</h4>
        <div class="option-container">
            <%= link_to 'Menu', {:controller => "welcome", :action => "menu"}, {:class => :'btn btn-lg btn-primary'} %>
            <%= link_to 'Contact', {:controller => "welcome", :action => "contact_us"}, {:class => :'btn btn-lg btn-primary'} %>
    </div>
</div>

<%= javascript_tag do %>
    $('#navbar li.home').addClass('active');
<% end %>

app/views/welcome/menu.html.erb
<div class="row">
    <ul class="nav nav-pills" role="tablist">
        <% SECTIONS.each do |section| %>
            <%= activeClass(section).html_safe %>
            <%= link_to section, {:action => 'menu', :section => section}, {:class => :'btn btn-lg'} %></li>
        <% end %>
    </ul>
</div>

<div class="row food-item-list "> 
    <div class="row">
        <div class="dropdown food-sort">
            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">Sort foods
            </button>
            <ul class="dropdown-menu">
                <% SORT_OPTION.each do |option| %>
                    <li><%= link_to option[:html].html_safe, setUrlParam('orderBy', option[:id]) %></li>
                <% end %>
                <li><%= link_to 'Clear Sort', setUrlParam('orderBy', nil) %></li>
            </ul>
        </div>

        <div class="dropdown food-sort">
            <button class="btn btn-info dropdown-toggle" type="button" data-toggle="dropdown">Filter foods
            </button>
            <ul class="dropdown-menu">
                <% FILTER_OPTION.each do |option| %>
                        <li><%= link_to option[:html].html_safe, setUrlParam('filterBy', option[:id]) %></li>
                <% end %>
                <li><%= link_to 'Clear Filter', setUrlParam('filterBy', nil) %></li>
            </ul>
        </div>
        
    </div>

    <div class="list-group col-md-6 food-list col-sm-12">
        <% @foods.each do |food| %>
            <a href="#" class="list-group-item" data-id="<%= food.id %>">
                <span>
                    <%= food.name %>
                    <span class="badge viewed-count"><%= food.num_of_viewed == nil ? 0 : food.num_of_viewed %></span>
                </span>
                <span class="badge price"><%= number_to_currency(food.price, precision: 1, unit: "VND", format: "%n %u") %></span>
            </a>
        <% end %>
    </div>
    <div class="food-details-container col-md-6 col-xs-12"></div>
</div>

<%= javascript_tag do %>
    window.foods =  <%= raw @foods.to_json %>
    $('#navbar li.menu').addClass('active');
<% end %>

<%= javascript_include_tag 'foods_menu' %>